// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: _rpc.proto

// Protobuf Java Version: 3.25.2
package com.trs.pacifica;

public final class RpcRequest {
  private RpcRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AppendEntriesRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jpacifica.AppendEntriesRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .jpacifica.ReplicaId primary_id = 1;</code>
     * @return Whether the primaryId field is set.
     */
    boolean hasPrimaryId();
    /**
     * <code>optional .jpacifica.ReplicaId primary_id = 1;</code>
     * @return The primaryId.
     */
    com.trs.pacifica.RpcCommon.ReplicaId getPrimaryId();
    /**
     * <code>optional .jpacifica.ReplicaId primary_id = 1;</code>
     */
    com.trs.pacifica.RpcCommon.ReplicaIdOrBuilder getPrimaryIdOrBuilder();

    /**
     * <code>optional .jpacifica.ReplicaId target_id = 2;</code>
     * @return Whether the targetId field is set.
     */
    boolean hasTargetId();
    /**
     * <code>optional .jpacifica.ReplicaId target_id = 2;</code>
     * @return The targetId.
     */
    com.trs.pacifica.RpcCommon.ReplicaId getTargetId();
    /**
     * <code>optional .jpacifica.ReplicaId target_id = 2;</code>
     */
    com.trs.pacifica.RpcCommon.ReplicaIdOrBuilder getTargetIdOrBuilder();

    /**
     * <code>optional int64 prev_log_index = 3;</code>
     * @return Whether the prevLogIndex field is set.
     */
    boolean hasPrevLogIndex();
    /**
     * <code>optional int64 prev_log_index = 3;</code>
     * @return The prevLogIndex.
     */
    long getPrevLogIndex();

    /**
     * <code>optional int64 prev_log_version = 4;</code>
     * @return Whether the prevLogVersion field is set.
     */
    boolean hasPrevLogVersion();
    /**
     * <code>optional int64 prev_log_version = 4;</code>
     * @return The prevLogVersion.
     */
    long getPrevLogVersion();

    /**
     * <code>optional int64 commit_point = 5;</code>
     * @return Whether the commitPoint field is set.
     */
    boolean hasCommitPoint();
    /**
     * <code>optional int64 commit_point = 5;</code>
     * @return The commitPoint.
     */
    long getCommitPoint();

    /**
     * <code>optional int64 version = 6;</code>
     * @return Whether the version field is set.
     */
    boolean hasVersion();
    /**
     * <code>optional int64 version = 6;</code>
     * @return The version.
     */
    long getVersion();

    /**
     * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
     */
    java.util.List<com.trs.pacifica.RpcCommon.LogEntryMeta> 
        getLogMetaList();
    /**
     * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
     */
    com.trs.pacifica.RpcCommon.LogEntryMeta getLogMeta(int index);
    /**
     * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
     */
    int getLogMetaCount();
    /**
     * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
     */
    java.util.List<? extends com.trs.pacifica.RpcCommon.LogEntryMetaOrBuilder> 
        getLogMetaOrBuilderList();
    /**
     * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
     */
    com.trs.pacifica.RpcCommon.LogEntryMetaOrBuilder getLogMetaOrBuilder(
        int index);

    /**
     * <code>optional bytes log_data = 8;</code>
     * @return Whether the logData field is set.
     */
    boolean hasLogData();
    /**
     * <code>optional bytes log_data = 8;</code>
     * @return The logData.
     */
    com.google.protobuf.ByteString getLogData();
  }
  /**
   * Protobuf type {@code jpacifica.AppendEntriesRequest}
   */
  public static final class AppendEntriesRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jpacifica.AppendEntriesRequest)
      AppendEntriesRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AppendEntriesRequest.newBuilder() to construct.
    private AppendEntriesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppendEntriesRequest() {
      logMeta_ = java.util.Collections.emptyList();
      logData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AppendEntriesRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trs.pacifica.RpcRequest.internal_static_jpacifica_AppendEntriesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trs.pacifica.RpcRequest.internal_static_jpacifica_AppendEntriesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trs.pacifica.RpcRequest.AppendEntriesRequest.class, com.trs.pacifica.RpcRequest.AppendEntriesRequest.Builder.class);
    }

    private int bitField0_;
    public static final int PRIMARY_ID_FIELD_NUMBER = 1;
    private com.trs.pacifica.RpcCommon.ReplicaId primaryId_;
    /**
     * <code>optional .jpacifica.ReplicaId primary_id = 1;</code>
     * @return Whether the primaryId field is set.
     */
    @java.lang.Override
    public boolean hasPrimaryId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .jpacifica.ReplicaId primary_id = 1;</code>
     * @return The primaryId.
     */
    @java.lang.Override
    public com.trs.pacifica.RpcCommon.ReplicaId getPrimaryId() {
      return primaryId_ == null ? com.trs.pacifica.RpcCommon.ReplicaId.getDefaultInstance() : primaryId_;
    }
    /**
     * <code>optional .jpacifica.ReplicaId primary_id = 1;</code>
     */
    @java.lang.Override
    public com.trs.pacifica.RpcCommon.ReplicaIdOrBuilder getPrimaryIdOrBuilder() {
      return primaryId_ == null ? com.trs.pacifica.RpcCommon.ReplicaId.getDefaultInstance() : primaryId_;
    }

    public static final int TARGET_ID_FIELD_NUMBER = 2;
    private com.trs.pacifica.RpcCommon.ReplicaId targetId_;
    /**
     * <code>optional .jpacifica.ReplicaId target_id = 2;</code>
     * @return Whether the targetId field is set.
     */
    @java.lang.Override
    public boolean hasTargetId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .jpacifica.ReplicaId target_id = 2;</code>
     * @return The targetId.
     */
    @java.lang.Override
    public com.trs.pacifica.RpcCommon.ReplicaId getTargetId() {
      return targetId_ == null ? com.trs.pacifica.RpcCommon.ReplicaId.getDefaultInstance() : targetId_;
    }
    /**
     * <code>optional .jpacifica.ReplicaId target_id = 2;</code>
     */
    @java.lang.Override
    public com.trs.pacifica.RpcCommon.ReplicaIdOrBuilder getTargetIdOrBuilder() {
      return targetId_ == null ? com.trs.pacifica.RpcCommon.ReplicaId.getDefaultInstance() : targetId_;
    }

    public static final int PREV_LOG_INDEX_FIELD_NUMBER = 3;
    private long prevLogIndex_ = 0L;
    /**
     * <code>optional int64 prev_log_index = 3;</code>
     * @return Whether the prevLogIndex field is set.
     */
    @java.lang.Override
    public boolean hasPrevLogIndex() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int64 prev_log_index = 3;</code>
     * @return The prevLogIndex.
     */
    @java.lang.Override
    public long getPrevLogIndex() {
      return prevLogIndex_;
    }

    public static final int PREV_LOG_VERSION_FIELD_NUMBER = 4;
    private long prevLogVersion_ = 0L;
    /**
     * <code>optional int64 prev_log_version = 4;</code>
     * @return Whether the prevLogVersion field is set.
     */
    @java.lang.Override
    public boolean hasPrevLogVersion() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int64 prev_log_version = 4;</code>
     * @return The prevLogVersion.
     */
    @java.lang.Override
    public long getPrevLogVersion() {
      return prevLogVersion_;
    }

    public static final int COMMIT_POINT_FIELD_NUMBER = 5;
    private long commitPoint_ = 0L;
    /**
     * <code>optional int64 commit_point = 5;</code>
     * @return Whether the commitPoint field is set.
     */
    @java.lang.Override
    public boolean hasCommitPoint() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int64 commit_point = 5;</code>
     * @return The commitPoint.
     */
    @java.lang.Override
    public long getCommitPoint() {
      return commitPoint_;
    }

    public static final int VERSION_FIELD_NUMBER = 6;
    private long version_ = 0L;
    /**
     * <code>optional int64 version = 6;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int64 version = 6;</code>
     * @return The version.
     */
    @java.lang.Override
    public long getVersion() {
      return version_;
    }

    public static final int LOG_META_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private java.util.List<com.trs.pacifica.RpcCommon.LogEntryMeta> logMeta_;
    /**
     * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
     */
    @java.lang.Override
    public java.util.List<com.trs.pacifica.RpcCommon.LogEntryMeta> getLogMetaList() {
      return logMeta_;
    }
    /**
     * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.trs.pacifica.RpcCommon.LogEntryMetaOrBuilder> 
        getLogMetaOrBuilderList() {
      return logMeta_;
    }
    /**
     * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
     */
    @java.lang.Override
    public int getLogMetaCount() {
      return logMeta_.size();
    }
    /**
     * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
     */
    @java.lang.Override
    public com.trs.pacifica.RpcCommon.LogEntryMeta getLogMeta(int index) {
      return logMeta_.get(index);
    }
    /**
     * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
     */
    @java.lang.Override
    public com.trs.pacifica.RpcCommon.LogEntryMetaOrBuilder getLogMetaOrBuilder(
        int index) {
      return logMeta_.get(index);
    }

    public static final int LOG_DATA_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString logData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes log_data = 8;</code>
     * @return Whether the logData field is set.
     */
    @java.lang.Override
    public boolean hasLogData() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional bytes log_data = 8;</code>
     * @return The logData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLogData() {
      return logData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getPrimaryId());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getTargetId());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, prevLogIndex_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt64(4, prevLogVersion_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt64(5, commitPoint_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt64(6, version_);
      }
      for (int i = 0; i < logMeta_.size(); i++) {
        output.writeMessage(7, logMeta_.get(i));
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeBytes(8, logData_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPrimaryId());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTargetId());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, prevLogIndex_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, prevLogVersion_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, commitPoint_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, version_);
      }
      for (int i = 0; i < logMeta_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, logMeta_.get(i));
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, logData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.trs.pacifica.RpcRequest.AppendEntriesRequest)) {
        return super.equals(obj);
      }
      com.trs.pacifica.RpcRequest.AppendEntriesRequest other = (com.trs.pacifica.RpcRequest.AppendEntriesRequest) obj;

      if (hasPrimaryId() != other.hasPrimaryId()) return false;
      if (hasPrimaryId()) {
        if (!getPrimaryId()
            .equals(other.getPrimaryId())) return false;
      }
      if (hasTargetId() != other.hasTargetId()) return false;
      if (hasTargetId()) {
        if (!getTargetId()
            .equals(other.getTargetId())) return false;
      }
      if (hasPrevLogIndex() != other.hasPrevLogIndex()) return false;
      if (hasPrevLogIndex()) {
        if (getPrevLogIndex()
            != other.getPrevLogIndex()) return false;
      }
      if (hasPrevLogVersion() != other.hasPrevLogVersion()) return false;
      if (hasPrevLogVersion()) {
        if (getPrevLogVersion()
            != other.getPrevLogVersion()) return false;
      }
      if (hasCommitPoint() != other.hasCommitPoint()) return false;
      if (hasCommitPoint()) {
        if (getCommitPoint()
            != other.getCommitPoint()) return false;
      }
      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (getVersion()
            != other.getVersion()) return false;
      }
      if (!getLogMetaList()
          .equals(other.getLogMetaList())) return false;
      if (hasLogData() != other.hasLogData()) return false;
      if (hasLogData()) {
        if (!getLogData()
            .equals(other.getLogData())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPrimaryId()) {
        hash = (37 * hash) + PRIMARY_ID_FIELD_NUMBER;
        hash = (53 * hash) + getPrimaryId().hashCode();
      }
      if (hasTargetId()) {
        hash = (37 * hash) + TARGET_ID_FIELD_NUMBER;
        hash = (53 * hash) + getTargetId().hashCode();
      }
      if (hasPrevLogIndex()) {
        hash = (37 * hash) + PREV_LOG_INDEX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPrevLogIndex());
      }
      if (hasPrevLogVersion()) {
        hash = (37 * hash) + PREV_LOG_VERSION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPrevLogVersion());
      }
      if (hasCommitPoint()) {
        hash = (37 * hash) + COMMIT_POINT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCommitPoint());
      }
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getVersion());
      }
      if (getLogMetaCount() > 0) {
        hash = (37 * hash) + LOG_META_FIELD_NUMBER;
        hash = (53 * hash) + getLogMetaList().hashCode();
      }
      if (hasLogData()) {
        hash = (37 * hash) + LOG_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getLogData().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.trs.pacifica.RpcRequest.AppendEntriesRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trs.pacifica.RpcRequest.AppendEntriesRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trs.pacifica.RpcRequest.AppendEntriesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trs.pacifica.RpcRequest.AppendEntriesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trs.pacifica.RpcRequest.AppendEntriesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trs.pacifica.RpcRequest.AppendEntriesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trs.pacifica.RpcRequest.AppendEntriesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.trs.pacifica.RpcRequest.AppendEntriesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.trs.pacifica.RpcRequest.AppendEntriesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.trs.pacifica.RpcRequest.AppendEntriesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.trs.pacifica.RpcRequest.AppendEntriesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.trs.pacifica.RpcRequest.AppendEntriesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.trs.pacifica.RpcRequest.AppendEntriesRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jpacifica.AppendEntriesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jpacifica.AppendEntriesRequest)
        com.trs.pacifica.RpcRequest.AppendEntriesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.trs.pacifica.RpcRequest.internal_static_jpacifica_AppendEntriesRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.trs.pacifica.RpcRequest.internal_static_jpacifica_AppendEntriesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.trs.pacifica.RpcRequest.AppendEntriesRequest.class, com.trs.pacifica.RpcRequest.AppendEntriesRequest.Builder.class);
      }

      // Construct using com.trs.pacifica.RpcRequest.AppendEntriesRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPrimaryIdFieldBuilder();
          getTargetIdFieldBuilder();
          getLogMetaFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        primaryId_ = null;
        if (primaryIdBuilder_ != null) {
          primaryIdBuilder_.dispose();
          primaryIdBuilder_ = null;
        }
        targetId_ = null;
        if (targetIdBuilder_ != null) {
          targetIdBuilder_.dispose();
          targetIdBuilder_ = null;
        }
        prevLogIndex_ = 0L;
        prevLogVersion_ = 0L;
        commitPoint_ = 0L;
        version_ = 0L;
        if (logMetaBuilder_ == null) {
          logMeta_ = java.util.Collections.emptyList();
        } else {
          logMeta_ = null;
          logMetaBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        logData_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.trs.pacifica.RpcRequest.internal_static_jpacifica_AppendEntriesRequest_descriptor;
      }

      @java.lang.Override
      public com.trs.pacifica.RpcRequest.AppendEntriesRequest getDefaultInstanceForType() {
        return com.trs.pacifica.RpcRequest.AppendEntriesRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.trs.pacifica.RpcRequest.AppendEntriesRequest build() {
        com.trs.pacifica.RpcRequest.AppendEntriesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.trs.pacifica.RpcRequest.AppendEntriesRequest buildPartial() {
        com.trs.pacifica.RpcRequest.AppendEntriesRequest result = new com.trs.pacifica.RpcRequest.AppendEntriesRequest(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.trs.pacifica.RpcRequest.AppendEntriesRequest result) {
        if (logMetaBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0)) {
            logMeta_ = java.util.Collections.unmodifiableList(logMeta_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.logMeta_ = logMeta_;
        } else {
          result.logMeta_ = logMetaBuilder_.build();
        }
      }

      private void buildPartial0(com.trs.pacifica.RpcRequest.AppendEntriesRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.primaryId_ = primaryIdBuilder_ == null
              ? primaryId_
              : primaryIdBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.targetId_ = targetIdBuilder_ == null
              ? targetId_
              : targetIdBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.prevLogIndex_ = prevLogIndex_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.prevLogVersion_ = prevLogVersion_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.commitPoint_ = commitPoint_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.version_ = version_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.logData_ = logData_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.trs.pacifica.RpcRequest.AppendEntriesRequest) {
          return mergeFrom((com.trs.pacifica.RpcRequest.AppendEntriesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.trs.pacifica.RpcRequest.AppendEntriesRequest other) {
        if (other == com.trs.pacifica.RpcRequest.AppendEntriesRequest.getDefaultInstance()) return this;
        if (other.hasPrimaryId()) {
          mergePrimaryId(other.getPrimaryId());
        }
        if (other.hasTargetId()) {
          mergeTargetId(other.getTargetId());
        }
        if (other.hasPrevLogIndex()) {
          setPrevLogIndex(other.getPrevLogIndex());
        }
        if (other.hasPrevLogVersion()) {
          setPrevLogVersion(other.getPrevLogVersion());
        }
        if (other.hasCommitPoint()) {
          setCommitPoint(other.getCommitPoint());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (logMetaBuilder_ == null) {
          if (!other.logMeta_.isEmpty()) {
            if (logMeta_.isEmpty()) {
              logMeta_ = other.logMeta_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureLogMetaIsMutable();
              logMeta_.addAll(other.logMeta_);
            }
            onChanged();
          }
        } else {
          if (!other.logMeta_.isEmpty()) {
            if (logMetaBuilder_.isEmpty()) {
              logMetaBuilder_.dispose();
              logMetaBuilder_ = null;
              logMeta_ = other.logMeta_;
              bitField0_ = (bitField0_ & ~0x00000040);
              logMetaBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLogMetaFieldBuilder() : null;
            } else {
              logMetaBuilder_.addAllMessages(other.logMeta_);
            }
          }
        }
        if (other.hasLogData()) {
          setLogData(other.getLogData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getPrimaryIdFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getTargetIdFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                prevLogIndex_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                prevLogVersion_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                commitPoint_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                version_ = input.readInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 58: {
                com.trs.pacifica.RpcCommon.LogEntryMeta m =
                    input.readMessage(
                        com.trs.pacifica.RpcCommon.LogEntryMeta.parser(),
                        extensionRegistry);
                if (logMetaBuilder_ == null) {
                  ensureLogMetaIsMutable();
                  logMeta_.add(m);
                } else {
                  logMetaBuilder_.addMessage(m);
                }
                break;
              } // case 58
              case 66: {
                logData_ = input.readBytes();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.trs.pacifica.RpcCommon.ReplicaId primaryId_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.trs.pacifica.RpcCommon.ReplicaId, com.trs.pacifica.RpcCommon.ReplicaId.Builder, com.trs.pacifica.RpcCommon.ReplicaIdOrBuilder> primaryIdBuilder_;
      /**
       * <code>optional .jpacifica.ReplicaId primary_id = 1;</code>
       * @return Whether the primaryId field is set.
       */
      public boolean hasPrimaryId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .jpacifica.ReplicaId primary_id = 1;</code>
       * @return The primaryId.
       */
      public com.trs.pacifica.RpcCommon.ReplicaId getPrimaryId() {
        if (primaryIdBuilder_ == null) {
          return primaryId_ == null ? com.trs.pacifica.RpcCommon.ReplicaId.getDefaultInstance() : primaryId_;
        } else {
          return primaryIdBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .jpacifica.ReplicaId primary_id = 1;</code>
       */
      public Builder setPrimaryId(com.trs.pacifica.RpcCommon.ReplicaId value) {
        if (primaryIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          primaryId_ = value;
        } else {
          primaryIdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .jpacifica.ReplicaId primary_id = 1;</code>
       */
      public Builder setPrimaryId(
          com.trs.pacifica.RpcCommon.ReplicaId.Builder builderForValue) {
        if (primaryIdBuilder_ == null) {
          primaryId_ = builderForValue.build();
        } else {
          primaryIdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .jpacifica.ReplicaId primary_id = 1;</code>
       */
      public Builder mergePrimaryId(com.trs.pacifica.RpcCommon.ReplicaId value) {
        if (primaryIdBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            primaryId_ != null &&
            primaryId_ != com.trs.pacifica.RpcCommon.ReplicaId.getDefaultInstance()) {
            getPrimaryIdBuilder().mergeFrom(value);
          } else {
            primaryId_ = value;
          }
        } else {
          primaryIdBuilder_.mergeFrom(value);
        }
        if (primaryId_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .jpacifica.ReplicaId primary_id = 1;</code>
       */
      public Builder clearPrimaryId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        primaryId_ = null;
        if (primaryIdBuilder_ != null) {
          primaryIdBuilder_.dispose();
          primaryIdBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .jpacifica.ReplicaId primary_id = 1;</code>
       */
      public com.trs.pacifica.RpcCommon.ReplicaId.Builder getPrimaryIdBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPrimaryIdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .jpacifica.ReplicaId primary_id = 1;</code>
       */
      public com.trs.pacifica.RpcCommon.ReplicaIdOrBuilder getPrimaryIdOrBuilder() {
        if (primaryIdBuilder_ != null) {
          return primaryIdBuilder_.getMessageOrBuilder();
        } else {
          return primaryId_ == null ?
              com.trs.pacifica.RpcCommon.ReplicaId.getDefaultInstance() : primaryId_;
        }
      }
      /**
       * <code>optional .jpacifica.ReplicaId primary_id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.trs.pacifica.RpcCommon.ReplicaId, com.trs.pacifica.RpcCommon.ReplicaId.Builder, com.trs.pacifica.RpcCommon.ReplicaIdOrBuilder> 
          getPrimaryIdFieldBuilder() {
        if (primaryIdBuilder_ == null) {
          primaryIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.trs.pacifica.RpcCommon.ReplicaId, com.trs.pacifica.RpcCommon.ReplicaId.Builder, com.trs.pacifica.RpcCommon.ReplicaIdOrBuilder>(
                  getPrimaryId(),
                  getParentForChildren(),
                  isClean());
          primaryId_ = null;
        }
        return primaryIdBuilder_;
      }

      private com.trs.pacifica.RpcCommon.ReplicaId targetId_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.trs.pacifica.RpcCommon.ReplicaId, com.trs.pacifica.RpcCommon.ReplicaId.Builder, com.trs.pacifica.RpcCommon.ReplicaIdOrBuilder> targetIdBuilder_;
      /**
       * <code>optional .jpacifica.ReplicaId target_id = 2;</code>
       * @return Whether the targetId field is set.
       */
      public boolean hasTargetId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .jpacifica.ReplicaId target_id = 2;</code>
       * @return The targetId.
       */
      public com.trs.pacifica.RpcCommon.ReplicaId getTargetId() {
        if (targetIdBuilder_ == null) {
          return targetId_ == null ? com.trs.pacifica.RpcCommon.ReplicaId.getDefaultInstance() : targetId_;
        } else {
          return targetIdBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .jpacifica.ReplicaId target_id = 2;</code>
       */
      public Builder setTargetId(com.trs.pacifica.RpcCommon.ReplicaId value) {
        if (targetIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          targetId_ = value;
        } else {
          targetIdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .jpacifica.ReplicaId target_id = 2;</code>
       */
      public Builder setTargetId(
          com.trs.pacifica.RpcCommon.ReplicaId.Builder builderForValue) {
        if (targetIdBuilder_ == null) {
          targetId_ = builderForValue.build();
        } else {
          targetIdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .jpacifica.ReplicaId target_id = 2;</code>
       */
      public Builder mergeTargetId(com.trs.pacifica.RpcCommon.ReplicaId value) {
        if (targetIdBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            targetId_ != null &&
            targetId_ != com.trs.pacifica.RpcCommon.ReplicaId.getDefaultInstance()) {
            getTargetIdBuilder().mergeFrom(value);
          } else {
            targetId_ = value;
          }
        } else {
          targetIdBuilder_.mergeFrom(value);
        }
        if (targetId_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .jpacifica.ReplicaId target_id = 2;</code>
       */
      public Builder clearTargetId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        targetId_ = null;
        if (targetIdBuilder_ != null) {
          targetIdBuilder_.dispose();
          targetIdBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .jpacifica.ReplicaId target_id = 2;</code>
       */
      public com.trs.pacifica.RpcCommon.ReplicaId.Builder getTargetIdBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getTargetIdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .jpacifica.ReplicaId target_id = 2;</code>
       */
      public com.trs.pacifica.RpcCommon.ReplicaIdOrBuilder getTargetIdOrBuilder() {
        if (targetIdBuilder_ != null) {
          return targetIdBuilder_.getMessageOrBuilder();
        } else {
          return targetId_ == null ?
              com.trs.pacifica.RpcCommon.ReplicaId.getDefaultInstance() : targetId_;
        }
      }
      /**
       * <code>optional .jpacifica.ReplicaId target_id = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.trs.pacifica.RpcCommon.ReplicaId, com.trs.pacifica.RpcCommon.ReplicaId.Builder, com.trs.pacifica.RpcCommon.ReplicaIdOrBuilder> 
          getTargetIdFieldBuilder() {
        if (targetIdBuilder_ == null) {
          targetIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.trs.pacifica.RpcCommon.ReplicaId, com.trs.pacifica.RpcCommon.ReplicaId.Builder, com.trs.pacifica.RpcCommon.ReplicaIdOrBuilder>(
                  getTargetId(),
                  getParentForChildren(),
                  isClean());
          targetId_ = null;
        }
        return targetIdBuilder_;
      }

      private long prevLogIndex_ ;
      /**
       * <code>optional int64 prev_log_index = 3;</code>
       * @return Whether the prevLogIndex field is set.
       */
      @java.lang.Override
      public boolean hasPrevLogIndex() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int64 prev_log_index = 3;</code>
       * @return The prevLogIndex.
       */
      @java.lang.Override
      public long getPrevLogIndex() {
        return prevLogIndex_;
      }
      /**
       * <code>optional int64 prev_log_index = 3;</code>
       * @param value The prevLogIndex to set.
       * @return This builder for chaining.
       */
      public Builder setPrevLogIndex(long value) {

        prevLogIndex_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 prev_log_index = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrevLogIndex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        prevLogIndex_ = 0L;
        onChanged();
        return this;
      }

      private long prevLogVersion_ ;
      /**
       * <code>optional int64 prev_log_version = 4;</code>
       * @return Whether the prevLogVersion field is set.
       */
      @java.lang.Override
      public boolean hasPrevLogVersion() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int64 prev_log_version = 4;</code>
       * @return The prevLogVersion.
       */
      @java.lang.Override
      public long getPrevLogVersion() {
        return prevLogVersion_;
      }
      /**
       * <code>optional int64 prev_log_version = 4;</code>
       * @param value The prevLogVersion to set.
       * @return This builder for chaining.
       */
      public Builder setPrevLogVersion(long value) {

        prevLogVersion_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 prev_log_version = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrevLogVersion() {
        bitField0_ = (bitField0_ & ~0x00000008);
        prevLogVersion_ = 0L;
        onChanged();
        return this;
      }

      private long commitPoint_ ;
      /**
       * <code>optional int64 commit_point = 5;</code>
       * @return Whether the commitPoint field is set.
       */
      @java.lang.Override
      public boolean hasCommitPoint() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int64 commit_point = 5;</code>
       * @return The commitPoint.
       */
      @java.lang.Override
      public long getCommitPoint() {
        return commitPoint_;
      }
      /**
       * <code>optional int64 commit_point = 5;</code>
       * @param value The commitPoint to set.
       * @return This builder for chaining.
       */
      public Builder setCommitPoint(long value) {

        commitPoint_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 commit_point = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommitPoint() {
        bitField0_ = (bitField0_ & ~0x00000010);
        commitPoint_ = 0L;
        onChanged();
        return this;
      }

      private long version_ ;
      /**
       * <code>optional int64 version = 6;</code>
       * @return Whether the version field is set.
       */
      @java.lang.Override
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int64 version = 6;</code>
       * @return The version.
       */
      @java.lang.Override
      public long getVersion() {
        return version_;
      }
      /**
       * <code>optional int64 version = 6;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(long value) {

        version_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 version = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000020);
        version_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.trs.pacifica.RpcCommon.LogEntryMeta> logMeta_ =
        java.util.Collections.emptyList();
      private void ensureLogMetaIsMutable() {
        if (!((bitField0_ & 0x00000040) != 0)) {
          logMeta_ = new java.util.ArrayList<com.trs.pacifica.RpcCommon.LogEntryMeta>(logMeta_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.trs.pacifica.RpcCommon.LogEntryMeta, com.trs.pacifica.RpcCommon.LogEntryMeta.Builder, com.trs.pacifica.RpcCommon.LogEntryMetaOrBuilder> logMetaBuilder_;

      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public java.util.List<com.trs.pacifica.RpcCommon.LogEntryMeta> getLogMetaList() {
        if (logMetaBuilder_ == null) {
          return java.util.Collections.unmodifiableList(logMeta_);
        } else {
          return logMetaBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public int getLogMetaCount() {
        if (logMetaBuilder_ == null) {
          return logMeta_.size();
        } else {
          return logMetaBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public com.trs.pacifica.RpcCommon.LogEntryMeta getLogMeta(int index) {
        if (logMetaBuilder_ == null) {
          return logMeta_.get(index);
        } else {
          return logMetaBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public Builder setLogMeta(
          int index, com.trs.pacifica.RpcCommon.LogEntryMeta value) {
        if (logMetaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogMetaIsMutable();
          logMeta_.set(index, value);
          onChanged();
        } else {
          logMetaBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public Builder setLogMeta(
          int index, com.trs.pacifica.RpcCommon.LogEntryMeta.Builder builderForValue) {
        if (logMetaBuilder_ == null) {
          ensureLogMetaIsMutable();
          logMeta_.set(index, builderForValue.build());
          onChanged();
        } else {
          logMetaBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public Builder addLogMeta(com.trs.pacifica.RpcCommon.LogEntryMeta value) {
        if (logMetaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogMetaIsMutable();
          logMeta_.add(value);
          onChanged();
        } else {
          logMetaBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public Builder addLogMeta(
          int index, com.trs.pacifica.RpcCommon.LogEntryMeta value) {
        if (logMetaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogMetaIsMutable();
          logMeta_.add(index, value);
          onChanged();
        } else {
          logMetaBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public Builder addLogMeta(
          com.trs.pacifica.RpcCommon.LogEntryMeta.Builder builderForValue) {
        if (logMetaBuilder_ == null) {
          ensureLogMetaIsMutable();
          logMeta_.add(builderForValue.build());
          onChanged();
        } else {
          logMetaBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public Builder addLogMeta(
          int index, com.trs.pacifica.RpcCommon.LogEntryMeta.Builder builderForValue) {
        if (logMetaBuilder_ == null) {
          ensureLogMetaIsMutable();
          logMeta_.add(index, builderForValue.build());
          onChanged();
        } else {
          logMetaBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public Builder addAllLogMeta(
          java.lang.Iterable<? extends com.trs.pacifica.RpcCommon.LogEntryMeta> values) {
        if (logMetaBuilder_ == null) {
          ensureLogMetaIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, logMeta_);
          onChanged();
        } else {
          logMetaBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public Builder clearLogMeta() {
        if (logMetaBuilder_ == null) {
          logMeta_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          logMetaBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public Builder removeLogMeta(int index) {
        if (logMetaBuilder_ == null) {
          ensureLogMetaIsMutable();
          logMeta_.remove(index);
          onChanged();
        } else {
          logMetaBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public com.trs.pacifica.RpcCommon.LogEntryMeta.Builder getLogMetaBuilder(
          int index) {
        return getLogMetaFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public com.trs.pacifica.RpcCommon.LogEntryMetaOrBuilder getLogMetaOrBuilder(
          int index) {
        if (logMetaBuilder_ == null) {
          return logMeta_.get(index);  } else {
          return logMetaBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public java.util.List<? extends com.trs.pacifica.RpcCommon.LogEntryMetaOrBuilder> 
           getLogMetaOrBuilderList() {
        if (logMetaBuilder_ != null) {
          return logMetaBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(logMeta_);
        }
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public com.trs.pacifica.RpcCommon.LogEntryMeta.Builder addLogMetaBuilder() {
        return getLogMetaFieldBuilder().addBuilder(
            com.trs.pacifica.RpcCommon.LogEntryMeta.getDefaultInstance());
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public com.trs.pacifica.RpcCommon.LogEntryMeta.Builder addLogMetaBuilder(
          int index) {
        return getLogMetaFieldBuilder().addBuilder(
            index, com.trs.pacifica.RpcCommon.LogEntryMeta.getDefaultInstance());
      }
      /**
       * <code>repeated .jpacifica.LogEntryMeta log_meta = 7;</code>
       */
      public java.util.List<com.trs.pacifica.RpcCommon.LogEntryMeta.Builder> 
           getLogMetaBuilderList() {
        return getLogMetaFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.trs.pacifica.RpcCommon.LogEntryMeta, com.trs.pacifica.RpcCommon.LogEntryMeta.Builder, com.trs.pacifica.RpcCommon.LogEntryMetaOrBuilder> 
          getLogMetaFieldBuilder() {
        if (logMetaBuilder_ == null) {
          logMetaBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.trs.pacifica.RpcCommon.LogEntryMeta, com.trs.pacifica.RpcCommon.LogEntryMeta.Builder, com.trs.pacifica.RpcCommon.LogEntryMetaOrBuilder>(
                  logMeta_,
                  ((bitField0_ & 0x00000040) != 0),
                  getParentForChildren(),
                  isClean());
          logMeta_ = null;
        }
        return logMetaBuilder_;
      }

      private com.google.protobuf.ByteString logData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes log_data = 8;</code>
       * @return Whether the logData field is set.
       */
      @java.lang.Override
      public boolean hasLogData() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional bytes log_data = 8;</code>
       * @return The logData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getLogData() {
        return logData_;
      }
      /**
       * <code>optional bytes log_data = 8;</code>
       * @param value The logData to set.
       * @return This builder for chaining.
       */
      public Builder setLogData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        logData_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes log_data = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogData() {
        bitField0_ = (bitField0_ & ~0x00000080);
        logData_ = getDefaultInstance().getLogData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jpacifica.AppendEntriesRequest)
    }

    // @@protoc_insertion_point(class_scope:jpacifica.AppendEntriesRequest)
    private static final com.trs.pacifica.RpcRequest.AppendEntriesRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.trs.pacifica.RpcRequest.AppendEntriesRequest();
    }

    public static com.trs.pacifica.RpcRequest.AppendEntriesRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppendEntriesRequest>
        PARSER = new com.google.protobuf.AbstractParser<AppendEntriesRequest>() {
      @java.lang.Override
      public AppendEntriesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AppendEntriesRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppendEntriesRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.trs.pacifica.RpcRequest.AppendEntriesRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jpacifica_AppendEntriesRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jpacifica_AppendEntriesRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\n_rpc.proto\022\tjpacifica\032\r_common.proto\"\221" +
      "\003\n\024AppendEntriesRequest\022-\n\nprimary_id\030\001 " +
      "\001(\0132\024.jpacifica.ReplicaIdH\000\210\001\001\022,\n\ttarget" +
      "_id\030\002 \001(\0132\024.jpacifica.ReplicaIdH\001\210\001\001\022\033\n\016" +
      "prev_log_index\030\003 \001(\003H\002\210\001\001\022\035\n\020prev_log_ve" +
      "rsion\030\004 \001(\003H\003\210\001\001\022\031\n\014commit_point\030\005 \001(\003H\004" +
      "\210\001\001\022\024\n\007version\030\006 \001(\003H\005\210\001\001\022)\n\010log_meta\030\007 " +
      "\003(\0132\027.jpacifica.LogEntryMeta\022\025\n\010log_data" +
      "\030\010 \001(\014H\006\210\001\001B\r\n\013_primary_idB\014\n\n_target_id" +
      "B\021\n\017_prev_log_indexB\023\n\021_prev_log_version" +
      "B\017\n\r_commit_pointB\n\n\010_versionB\013\n\t_log_da" +
      "taB\036\n\020com.trs.pacificaB\nRpcRequestb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.trs.pacifica.RpcCommon.getDescriptor(),
        });
    internal_static_jpacifica_AppendEntriesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jpacifica_AppendEntriesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jpacifica_AppendEntriesRequest_descriptor,
        new java.lang.String[] { "PrimaryId", "TargetId", "PrevLogIndex", "PrevLogVersion", "CommitPoint", "Version", "LogMeta", "LogData", });
    com.trs.pacifica.RpcCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
