// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: _common.proto

// Protobuf Java Version: 3.25.2
package com.trs.pacifica.proto;

public final class RpcCommon {
  private RpcCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReplicaIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jpacifica.ReplicaId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string group_name = 1;</code>
     * @return Whether the groupName field is set.
     */
    boolean hasGroupName();
    /**
     * <code>optional string group_name = 1;</code>
     * @return The groupName.
     */
    java.lang.String getGroupName();
    /**
     * <code>optional string group_name = 1;</code>
     * @return The bytes for groupName.
     */
    com.google.protobuf.ByteString
        getGroupNameBytes();

    /**
     * <code>optional string node_id = 2;</code>
     * @return Whether the nodeId field is set.
     */
    boolean hasNodeId();
    /**
     * <code>optional string node_id = 2;</code>
     * @return The nodeId.
     */
    java.lang.String getNodeId();
    /**
     * <code>optional string node_id = 2;</code>
     * @return The bytes for nodeId.
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();
  }
  /**
   * Protobuf type {@code jpacifica.ReplicaId}
   */
  public static final class ReplicaId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jpacifica.ReplicaId)
      ReplicaIdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReplicaId.newBuilder() to construct.
    private ReplicaId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReplicaId() {
      groupName_ = "";
      nodeId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReplicaId();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trs.pacifica.proto.RpcCommon.internal_static_jpacifica_ReplicaId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trs.pacifica.proto.RpcCommon.internal_static_jpacifica_ReplicaId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trs.pacifica.proto.RpcCommon.ReplicaId.class, com.trs.pacifica.proto.RpcCommon.ReplicaId.Builder.class);
    }

    private int bitField0_;
    public static final int GROUP_NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object groupName_ = "";
    /**
     * <code>optional string group_name = 1;</code>
     * @return Whether the groupName field is set.
     */
    @java.lang.Override
    public boolean hasGroupName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string group_name = 1;</code>
     * @return The groupName.
     */
    @java.lang.Override
    public java.lang.String getGroupName() {
      java.lang.Object ref = groupName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string group_name = 1;</code>
     * @return The bytes for groupName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGroupNameBytes() {
      java.lang.Object ref = groupName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODE_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nodeId_ = "";
    /**
     * <code>optional string node_id = 2;</code>
     * @return Whether the nodeId field is set.
     */
    @java.lang.Override
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string node_id = 2;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string node_id = 2;</code>
     * @return The bytes for nodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, groupName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nodeId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, groupName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nodeId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.trs.pacifica.proto.RpcCommon.ReplicaId)) {
        return super.equals(obj);
      }
      com.trs.pacifica.proto.RpcCommon.ReplicaId other = (com.trs.pacifica.proto.RpcCommon.ReplicaId) obj;

      if (hasGroupName() != other.hasGroupName()) return false;
      if (hasGroupName()) {
        if (!getGroupName()
            .equals(other.getGroupName())) return false;
      }
      if (hasNodeId() != other.hasNodeId()) return false;
      if (hasNodeId()) {
        if (!getNodeId()
            .equals(other.getNodeId())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGroupName()) {
        hash = (37 * hash) + GROUP_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getGroupName().hashCode();
      }
      if (hasNodeId()) {
        hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getNodeId().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.trs.pacifica.proto.RpcCommon.ReplicaId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trs.pacifica.proto.RpcCommon.ReplicaId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trs.pacifica.proto.RpcCommon.ReplicaId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trs.pacifica.proto.RpcCommon.ReplicaId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trs.pacifica.proto.RpcCommon.ReplicaId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trs.pacifica.proto.RpcCommon.ReplicaId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trs.pacifica.proto.RpcCommon.ReplicaId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.trs.pacifica.proto.RpcCommon.ReplicaId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.trs.pacifica.proto.RpcCommon.ReplicaId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.trs.pacifica.proto.RpcCommon.ReplicaId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.trs.pacifica.proto.RpcCommon.ReplicaId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.trs.pacifica.proto.RpcCommon.ReplicaId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.trs.pacifica.proto.RpcCommon.ReplicaId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jpacifica.ReplicaId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jpacifica.ReplicaId)
        com.trs.pacifica.proto.RpcCommon.ReplicaIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.trs.pacifica.proto.RpcCommon.internal_static_jpacifica_ReplicaId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.trs.pacifica.proto.RpcCommon.internal_static_jpacifica_ReplicaId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.trs.pacifica.proto.RpcCommon.ReplicaId.class, com.trs.pacifica.proto.RpcCommon.ReplicaId.Builder.class);
      }

      // Construct using com.trs.pacifica.proto.RpcCommon.ReplicaId.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        groupName_ = "";
        nodeId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.trs.pacifica.proto.RpcCommon.internal_static_jpacifica_ReplicaId_descriptor;
      }

      @java.lang.Override
      public com.trs.pacifica.proto.RpcCommon.ReplicaId getDefaultInstanceForType() {
        return com.trs.pacifica.proto.RpcCommon.ReplicaId.getDefaultInstance();
      }

      @java.lang.Override
      public com.trs.pacifica.proto.RpcCommon.ReplicaId build() {
        com.trs.pacifica.proto.RpcCommon.ReplicaId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.trs.pacifica.proto.RpcCommon.ReplicaId buildPartial() {
        com.trs.pacifica.proto.RpcCommon.ReplicaId result = new com.trs.pacifica.proto.RpcCommon.ReplicaId(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.trs.pacifica.proto.RpcCommon.ReplicaId result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.groupName_ = groupName_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.nodeId_ = nodeId_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.trs.pacifica.proto.RpcCommon.ReplicaId) {
          return mergeFrom((com.trs.pacifica.proto.RpcCommon.ReplicaId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.trs.pacifica.proto.RpcCommon.ReplicaId other) {
        if (other == com.trs.pacifica.proto.RpcCommon.ReplicaId.getDefaultInstance()) return this;
        if (other.hasGroupName()) {
          groupName_ = other.groupName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasNodeId()) {
          nodeId_ = other.nodeId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                groupName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                nodeId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object groupName_ = "";
      /**
       * <code>optional string group_name = 1;</code>
       * @return Whether the groupName field is set.
       */
      public boolean hasGroupName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string group_name = 1;</code>
       * @return The groupName.
       */
      public java.lang.String getGroupName() {
        java.lang.Object ref = groupName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string group_name = 1;</code>
       * @return The bytes for groupName.
       */
      public com.google.protobuf.ByteString
          getGroupNameBytes() {
        java.lang.Object ref = groupName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string group_name = 1;</code>
       * @param value The groupName to set.
       * @return This builder for chaining.
       */
      public Builder setGroupName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        groupName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string group_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupName() {
        groupName_ = getDefaultInstance().getGroupName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string group_name = 1;</code>
       * @param value The bytes for groupName to set.
       * @return This builder for chaining.
       */
      public Builder setGroupNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        groupName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object nodeId_ = "";
      /**
       * <code>optional string node_id = 2;</code>
       * @return Whether the nodeId field is set.
       */
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string node_id = 2;</code>
       * @return The nodeId.
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string node_id = 2;</code>
       * @return The bytes for nodeId.
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string node_id = 2;</code>
       * @param value The nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nodeId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string node_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeId() {
        nodeId_ = getDefaultInstance().getNodeId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string node_id = 2;</code>
       * @param value The bytes for nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nodeId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jpacifica.ReplicaId)
    }

    // @@protoc_insertion_point(class_scope:jpacifica.ReplicaId)
    private static final com.trs.pacifica.proto.RpcCommon.ReplicaId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.trs.pacifica.proto.RpcCommon.ReplicaId();
    }

    public static com.trs.pacifica.proto.RpcCommon.ReplicaId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReplicaId>
        PARSER = new com.google.protobuf.AbstractParser<ReplicaId>() {
      @java.lang.Override
      public ReplicaId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReplicaId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReplicaId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.trs.pacifica.proto.RpcCommon.ReplicaId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LogEntryMetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jpacifica.LogEntryMeta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 version = 1;</code>
     * @return Whether the version field is set.
     */
    boolean hasVersion();
    /**
     * <code>optional int64 version = 1;</code>
     * @return The version.
     */
    long getVersion();

    /**
     * <code>optional int64 data_len = 2;</code>
     * @return Whether the dataLen field is set.
     */
    boolean hasDataLen();
    /**
     * <code>optional int64 data_len = 2;</code>
     * @return The dataLen.
     */
    long getDataLen();

    /**
     * <code>optional int64 type = 3;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional int64 type = 3;</code>
     * @return The type.
     */
    long getType();

    /**
     * <code>optional int64 checksum = 4;</code>
     * @return Whether the checksum field is set.
     */
    boolean hasChecksum();
    /**
     * <code>optional int64 checksum = 4;</code>
     * @return The checksum.
     */
    long getChecksum();
  }
  /**
   * Protobuf type {@code jpacifica.LogEntryMeta}
   */
  public static final class LogEntryMeta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jpacifica.LogEntryMeta)
      LogEntryMetaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogEntryMeta.newBuilder() to construct.
    private LogEntryMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogEntryMeta() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LogEntryMeta();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trs.pacifica.proto.RpcCommon.internal_static_jpacifica_LogEntryMeta_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trs.pacifica.proto.RpcCommon.internal_static_jpacifica_LogEntryMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trs.pacifica.proto.RpcCommon.LogEntryMeta.class, com.trs.pacifica.proto.RpcCommon.LogEntryMeta.Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private long version_ = 0L;
    /**
     * <code>optional int64 version = 1;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public long getVersion() {
      return version_;
    }

    public static final int DATA_LEN_FIELD_NUMBER = 2;
    private long dataLen_ = 0L;
    /**
     * <code>optional int64 data_len = 2;</code>
     * @return Whether the dataLen field is set.
     */
    @java.lang.Override
    public boolean hasDataLen() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 data_len = 2;</code>
     * @return The dataLen.
     */
    @java.lang.Override
    public long getDataLen() {
      return dataLen_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private long type_ = 0L;
    /**
     * <code>optional int64 type = 3;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int64 type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public long getType() {
      return type_;
    }

    public static final int CHECKSUM_FIELD_NUMBER = 4;
    private long checksum_ = 0L;
    /**
     * <code>optional int64 checksum = 4;</code>
     * @return Whether the checksum field is set.
     */
    @java.lang.Override
    public boolean hasChecksum() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int64 checksum = 4;</code>
     * @return The checksum.
     */
    @java.lang.Override
    public long getChecksum() {
      return checksum_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, version_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, dataLen_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, type_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt64(4, checksum_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, dataLen_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, type_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, checksum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.trs.pacifica.proto.RpcCommon.LogEntryMeta)) {
        return super.equals(obj);
      }
      com.trs.pacifica.proto.RpcCommon.LogEntryMeta other = (com.trs.pacifica.proto.RpcCommon.LogEntryMeta) obj;

      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (getVersion()
            != other.getVersion()) return false;
      }
      if (hasDataLen() != other.hasDataLen()) return false;
      if (hasDataLen()) {
        if (getDataLen()
            != other.getDataLen()) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (getType()
            != other.getType()) return false;
      }
      if (hasChecksum() != other.hasChecksum()) return false;
      if (hasChecksum()) {
        if (getChecksum()
            != other.getChecksum()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getVersion());
      }
      if (hasDataLen()) {
        hash = (37 * hash) + DATA_LEN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getDataLen());
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getType());
      }
      if (hasChecksum()) {
        hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getChecksum());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.trs.pacifica.proto.RpcCommon.LogEntryMeta parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trs.pacifica.proto.RpcCommon.LogEntryMeta parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trs.pacifica.proto.RpcCommon.LogEntryMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trs.pacifica.proto.RpcCommon.LogEntryMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trs.pacifica.proto.RpcCommon.LogEntryMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trs.pacifica.proto.RpcCommon.LogEntryMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trs.pacifica.proto.RpcCommon.LogEntryMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.trs.pacifica.proto.RpcCommon.LogEntryMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.trs.pacifica.proto.RpcCommon.LogEntryMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.trs.pacifica.proto.RpcCommon.LogEntryMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.trs.pacifica.proto.RpcCommon.LogEntryMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.trs.pacifica.proto.RpcCommon.LogEntryMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.trs.pacifica.proto.RpcCommon.LogEntryMeta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jpacifica.LogEntryMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jpacifica.LogEntryMeta)
        com.trs.pacifica.proto.RpcCommon.LogEntryMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.trs.pacifica.proto.RpcCommon.internal_static_jpacifica_LogEntryMeta_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.trs.pacifica.proto.RpcCommon.internal_static_jpacifica_LogEntryMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.trs.pacifica.proto.RpcCommon.LogEntryMeta.class, com.trs.pacifica.proto.RpcCommon.LogEntryMeta.Builder.class);
      }

      // Construct using com.trs.pacifica.proto.RpcCommon.LogEntryMeta.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        version_ = 0L;
        dataLen_ = 0L;
        type_ = 0L;
        checksum_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.trs.pacifica.proto.RpcCommon.internal_static_jpacifica_LogEntryMeta_descriptor;
      }

      @java.lang.Override
      public com.trs.pacifica.proto.RpcCommon.LogEntryMeta getDefaultInstanceForType() {
        return com.trs.pacifica.proto.RpcCommon.LogEntryMeta.getDefaultInstance();
      }

      @java.lang.Override
      public com.trs.pacifica.proto.RpcCommon.LogEntryMeta build() {
        com.trs.pacifica.proto.RpcCommon.LogEntryMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.trs.pacifica.proto.RpcCommon.LogEntryMeta buildPartial() {
        com.trs.pacifica.proto.RpcCommon.LogEntryMeta result = new com.trs.pacifica.proto.RpcCommon.LogEntryMeta(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.trs.pacifica.proto.RpcCommon.LogEntryMeta result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.version_ = version_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.dataLen_ = dataLen_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.checksum_ = checksum_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.trs.pacifica.proto.RpcCommon.LogEntryMeta) {
          return mergeFrom((com.trs.pacifica.proto.RpcCommon.LogEntryMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.trs.pacifica.proto.RpcCommon.LogEntryMeta other) {
        if (other == com.trs.pacifica.proto.RpcCommon.LogEntryMeta.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasDataLen()) {
          setDataLen(other.getDataLen());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasChecksum()) {
          setChecksum(other.getChecksum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                version_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                dataLen_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                type_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                checksum_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long version_ ;
      /**
       * <code>optional int64 version = 1;</code>
       * @return Whether the version field is set.
       */
      @java.lang.Override
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int64 version = 1;</code>
       * @return The version.
       */
      @java.lang.Override
      public long getVersion() {
        return version_;
      }
      /**
       * <code>optional int64 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(long value) {

        version_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0L;
        onChanged();
        return this;
      }

      private long dataLen_ ;
      /**
       * <code>optional int64 data_len = 2;</code>
       * @return Whether the dataLen field is set.
       */
      @java.lang.Override
      public boolean hasDataLen() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int64 data_len = 2;</code>
       * @return The dataLen.
       */
      @java.lang.Override
      public long getDataLen() {
        return dataLen_;
      }
      /**
       * <code>optional int64 data_len = 2;</code>
       * @param value The dataLen to set.
       * @return This builder for chaining.
       */
      public Builder setDataLen(long value) {

        dataLen_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 data_len = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataLen() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dataLen_ = 0L;
        onChanged();
        return this;
      }

      private long type_ ;
      /**
       * <code>optional int64 type = 3;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int64 type = 3;</code>
       * @return The type.
       */
      @java.lang.Override
      public long getType() {
        return type_;
      }
      /**
       * <code>optional int64 type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(long value) {

        type_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0L;
        onChanged();
        return this;
      }

      private long checksum_ ;
      /**
       * <code>optional int64 checksum = 4;</code>
       * @return Whether the checksum field is set.
       */
      @java.lang.Override
      public boolean hasChecksum() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int64 checksum = 4;</code>
       * @return The checksum.
       */
      @java.lang.Override
      public long getChecksum() {
        return checksum_;
      }
      /**
       * <code>optional int64 checksum = 4;</code>
       * @param value The checksum to set.
       * @return This builder for chaining.
       */
      public Builder setChecksum(long value) {

        checksum_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 checksum = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearChecksum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        checksum_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jpacifica.LogEntryMeta)
    }

    // @@protoc_insertion_point(class_scope:jpacifica.LogEntryMeta)
    private static final com.trs.pacifica.proto.RpcCommon.LogEntryMeta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.trs.pacifica.proto.RpcCommon.LogEntryMeta();
    }

    public static com.trs.pacifica.proto.RpcCommon.LogEntryMeta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogEntryMeta>
        PARSER = new com.google.protobuf.AbstractParser<LogEntryMeta>() {
      @java.lang.Override
      public LogEntryMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LogEntryMeta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogEntryMeta> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.trs.pacifica.proto.RpcCommon.LogEntryMeta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jpacifica_ReplicaId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jpacifica_ReplicaId_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jpacifica_LogEntryMeta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jpacifica_LogEntryMeta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\r_common.proto\022\tjpacifica\"U\n\tReplicaId\022" +
      "\027\n\ngroup_name\030\001 \001(\tH\000\210\001\001\022\024\n\007node_id\030\002 \001(" +
      "\tH\001\210\001\001B\r\n\013_group_nameB\n\n\010_node_id\"\224\001\n\014Lo" +
      "gEntryMeta\022\024\n\007version\030\001 \001(\003H\000\210\001\001\022\025\n\010data" +
      "_len\030\002 \001(\003H\001\210\001\001\022\021\n\004type\030\003 \001(\003H\002\210\001\001\022\025\n\010ch" +
      "ecksum\030\004 \001(\003H\003\210\001\001B\n\n\010_versionB\013\n\t_data_l" +
      "enB\007\n\005_typeB\013\n\t_checksumB#\n\026com.trs.paci" +
      "fica.protoB\tRpcCommonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_jpacifica_ReplicaId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jpacifica_ReplicaId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jpacifica_ReplicaId_descriptor,
        new java.lang.String[] { "GroupName", "NodeId", });
    internal_static_jpacifica_LogEntryMeta_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_jpacifica_LogEntryMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jpacifica_LogEntryMeta_descriptor,
        new java.lang.String[] { "Version", "DataLen", "Type", "Checksum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
